[package]
name = "stdpython"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = {version = "0.20", features=["auto-initialize",]}
#python-mod = "0.1.0"
python-mod = {path = "../python-mod-rs", version = "0.1.4"}
